name: "📊 performance matrix"
on:
  workflow_dispatch:

concurrency:
  group: perf-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  bench:
    name: "📊 bench - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2025
          - macos-15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: "🔄 Install the latest version of uv"
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: false
      - name: "🧪 Install tox"
        run: uv tool install --python-preference only-managed --python 3.14 tox --with tox-uv
      - name: "📊 Measure the performance matrix"
        run: tox run -e bench
        env:
          UV_PYTHON_PREFERENCE: only-managed
